In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("googleplaystore.csv")

In [4]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [5]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [6]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [7]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [9]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [10]:
# Find the highest-rated apps
df[["Rating","App"]].sort_values(by=["Rating","App"],ascending=False).head()

       Rating                                      App
10472    19.0  Life Made WI-Fi Touchscreen Photo Frame
5482      5.0               meStudying: AP English Lit
7756      5.0                                  iReadMe
6030      5.0                            iCard BD Plus
9178      5.0                                  i am EB

In [11]:
df[["Rating","App"]].max()

Rating                                                19.0
App       🔥 Football Wallpapers 4K | Full HD Backgrounds 😍
dtype: object

In [12]:
# Which category has the most apps?
df["Category"].value_counts().head(1)

Category
FAMILY    1972
Name: count, dtype: int64

In [13]:
# Average rating by category
df.groupby("Category")["Rating"].mean()

Category
1.9                    19.000000
ART_AND_DESIGN          4.358065
AUTO_AND_VEHICLES       4.190411
BEAUTY                  4.278571
BOOKS_AND_REFERENCE     4.346067
BUSINESS                4.121452
COMICS                  4.155172
COMMUNICATION           4.158537
DATING                  3.970769
EDUCATION               4.389032
ENTERTAINMENT           4.126174
EVENTS                  4.435556
FAMILY                  4.192272
FINANCE                 4.131889
FOOD_AND_DRINK          4.166972
GAME                    4.286326
HEALTH_AND_FITNESS      4.277104
HOUSE_AND_HOME          4.197368
LIBRARIES_AND_DEMO      4.178462
LIFESTYLE               4.094904
MAPS_AND_NAVIGATION     4.051613
MEDICAL                 4.189143
NEWS_AND_MAGAZINES      4.132189
PARENTING               4.300000
PERSONALIZATION         4.335987
PHOTOGRAPHY             4.192114
PRODUCTIVITY            4.211396
SHOPPING                4.259664
SOCIAL                  4.255598
SPORTS                  4.223511
TOOLS                   4.047411
TRAVEL_AND_LOCAL        4.109292
VIDEO_PLAYERS           4.063750
WEATHER                 4.244000
Name: Rating, dtype: float64

In [14]:
# Free vs paid app analysis
df["Type"].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [15]:
# Most reviewed apps
df[["Reviews","App"]].sort_values(by="Reviews" ,ascending=False).head(5)

     Reviews                                App
2989    9992             GollerCepte Live Score
4970     999       Ad Block REMOVER - NEED ROOT
2723    9975                SnipSnap Coupon App
2705    9975                SnipSnap Coupon App
3079    9971  US Open Tennis Championships 2018

In [16]:
# Data cleaning and EDA

In [17]:
df.shape

(10841, 13)

In [18]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [19]:
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [20]:
df["Category"].unique()

<StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
                 '1.9']
Length: 34, dtype: str

In [21]:
df["Category"].value_counts().head(1)

Category
FAMILY    1972
Name: count, dtype: int64

In [22]:
df["Rating"].mean()

np.float64(4.193338315362443)

In [23]:
df[df["Rating"]==df["Rating"].max()][["App","Rating"]]

                                           App  Rating
10472  Life Made WI-Fi Touchscreen Photo Frame    19.0

In [24]:
df[df["Rating"]==df["Rating"].min()][["App","Rating"]]

                                                    App  Rating
625                             House party - live chat     1.0
4127                                  Speech Therapy: F     1.0
5151                                      Clarksburg AH     1.0
5978                      Truck Driving Test Class 3 BC     1.0
6319                   BJ Bridge Standard American 2018     1.0
6490                                             MbH BM     1.0
7144                                      CB Mobile Biz     1.0
7383                                     Thistletown CI     1.0
7427                                     CJ DVD Rentals     1.0
7806                                        CR Magazine     1.0
7926                               Tech CU Card Manager     1.0
8820                                     DS Creator 2.0     1.0
8875                                     DT future1 cam     1.0
10324                    FE Mechanical Engineering Prep     1.0
10400           Familial Hypercholesterolaemia Handbook     1.0
10591  Lottery Ticket Checker - Florida Results & Lotto     1.0

In [25]:
df["Rating"].value_counts().sort_index()

Rating
1.0       16
1.2        1
1.4        3
1.5        3
1.6        4
1.7        8
1.8        8
1.9       13
2.0       12
2.1        8
2.2       14
2.3       20
2.4       19
2.5       21
2.6       25
2.7       25
2.8       42
2.9       45
3.0       83
3.1       69
3.2       64
3.3      102
3.4      128
3.5      163
3.6      174
3.7      239
3.8      303
3.9      386
4.0      568
4.1      708
4.2      952
4.3     1076
4.4     1109
4.5     1038
4.6      823
4.7      499
4.8      234
4.9       87
5.0      274
19.0       1
Name: count, dtype: int64

In [26]:
# most reviewed apps
df["Reviews"]=pd.to_numeric(df["Reviews"]).nlargest(10,"Reviews")[["App","Reviews"]]

ValueError: Unable to parse string "3.0M" at position 10472

In [27]:
df.sort_values("Size",ascending=False).head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3675,VLC for Android,VIDEO_PLAYERS,4.4,1032076,Varies with device,"100,000,000+",Free,0,Everyone,Video Players & Editors,"July 30, 2018",Varies with device,2.3 and up
9575,Red Hands – 2-Player Games,GAME,4.2,93608,Varies with device,"10,000,000+",Free,0,Everyone,Action,"February 9, 2018",Varies with device,Varies with device
5779,AW - Le News di AndroidWorld,NEWS_AND_MAGAZINES,4.1,2808,Varies with device,"100,000+",Free,0,Everyone,News & Magazines,"February 8, 2016",Varies with device,Varies with device
5778,ByssWeather for Wear OS,WEATHER,4.2,19666,Varies with device,"1,000,000+",Free,0,Everyone,Weather,"April 11, 2018",Varies with device,Varies with device
5773,Bits Watch Face,PRODUCTIVITY,4.0,6205,Varies with device,"100,000+",Free,0,Everyone,Productivity,"February 5, 2018",Varies with device,Varies with device

In [28]:
df["Size"]=df["Size"].str.replace("M","")
df["Size"]=df["Size"].str.replace("k","")
df["Size"]=pd.to_numeric(df["Size"],errors="coerce")
df.groupby("Category")["Size"].mean()

Category
1.9                           NaN
ART_AND_DESIGN          12.370968
AUTO_AND_VEHICLES       34.502667
BEAUTY                  13.795745
BOOKS_AND_REFERENCE     40.349746
BUSINESS                26.622500
COMICS                  34.111765
COMMUNICATION           55.786792
DATING                  16.710377
EDUCATION               30.528829
ENTERTAINMENT           21.853333
EVENTS                  19.817544
FAMILY                  38.007697
FINANCE                 28.894788
FOOD_AND_DRINK          22.185000
GAME                    45.797241
HEALTH_AND_FITNESS      38.178030
HOUSE_AND_HOME          25.616176
LIBRARIES_AND_DEMO     180.834146
LIFESTYLE               31.265507
MAPS_AND_NAVIGATION     31.312963
MEDICAL                 44.495853
NEWS_AND_MAGAZINES      14.448148
PARENTING               22.512963
PERSONALIZATION         42.655493
PHOTOGRAPHY             21.249606
PRODUCTIVITY            35.628713
SHOPPING                31.886070
SOCIAL                  26.211429
SPORTS                  32.475563
TOOLS                   47.776861
TRAVEL_AND_LOCAL        26.022917
VIDEO_PLAYERS           22.032824
WEATHER                 23.324561
Name: Size, dtype: float64

In [29]:
# most installed apps
df["Installs"]=pd.to_numeric(df["Installs"],errors="coerce")
df.nlargest(10,"Installs")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,NaN,0,NaN,0.0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,NaN,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,NaN,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,NaN,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,NaN,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,NaN,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6,NaN,Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19.0,NaN,Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29.0,NaN,Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33.0,NaN,Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up

In [30]:
df["Installs"]=pd.to_numeric(df["Installs"])
df.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size              float64
Installs          float64
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

In [31]:
df.groupby("Category")["Installs"].mean().sort_values(ascending=False)

Category
FAMILY                 0.0
1.9                    NaN
ART_AND_DESIGN         NaN
AUTO_AND_VEHICLES      NaN
BEAUTY                 NaN
BOOKS_AND_REFERENCE    NaN
BUSINESS               NaN
COMICS                 NaN
COMMUNICATION          NaN
DATING                 NaN
EDUCATION              NaN
ENTERTAINMENT          NaN
EVENTS                 NaN
FINANCE                NaN
FOOD_AND_DRINK         NaN
GAME                   NaN
HEALTH_AND_FITNESS     NaN
HOUSE_AND_HOME         NaN
LIBRARIES_AND_DEMO     NaN
LIFESTYLE              NaN
MAPS_AND_NAVIGATION    NaN
MEDICAL                NaN
NEWS_AND_MAGAZINES     NaN
PARENTING              NaN
PERSONALIZATION        NaN
PHOTOGRAPHY            NaN
PRODUCTIVITY           NaN
SHOPPING               NaN
SOCIAL                 NaN
SPORTS                 NaN
TOOLS                  NaN
TRAVEL_AND_LOCAL       NaN
VIDEO_PLAYERS          NaN
WEATHER                NaN
Name: Installs, dtype: float64

In [32]:
df.dropna().sum()

App
Category
Rating            0.0
Reviews
Size              0.0
Installs          0.0
Type
Price
Content Rating
Genres
Last Updated
Current Ver
Android Ver
dtype: object

In [33]:
df.groupby("Category")["Installs"].mean().sort_values(ascending=False)

Category
FAMILY                 0.0
1.9                    NaN
ART_AND_DESIGN         NaN
AUTO_AND_VEHICLES      NaN
BEAUTY                 NaN
BOOKS_AND_REFERENCE    NaN
BUSINESS               NaN
COMICS                 NaN
COMMUNICATION          NaN
DATING                 NaN
EDUCATION              NaN
ENTERTAINMENT          NaN
EVENTS                 NaN
FINANCE                NaN
FOOD_AND_DRINK         NaN
GAME                   NaN
HEALTH_AND_FITNESS     NaN
HOUSE_AND_HOME         NaN
LIBRARIES_AND_DEMO     NaN
LIFESTYLE              NaN
MAPS_AND_NAVIGATION    NaN
MEDICAL                NaN
NEWS_AND_MAGAZINES     NaN
PARENTING              NaN
PERSONALIZATION        NaN
PHOTOGRAPHY            NaN
PRODUCTIVITY           NaN
SHOPPING               NaN
SOCIAL                 NaN
SPORTS                 NaN
TOOLS                  NaN
TRAVEL_AND_LOCAL       NaN
VIDEO_PLAYERS          NaN
WEATHER                NaN
Name: Installs, dtype: float64

In [34]:
df.describe(include='all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,9145.000000,1.0,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,NaN,NaN,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,NaN,NaN,Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,NaN,NaN,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,37.035440,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,98.873769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,5.600000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,15.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,34.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,1020.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# count numerical and categorical columns
num_cols=df.select_dtypes(include='number').columns
print(num_cols)
cat_cols=df.select_dtypes(include="object").columns
print(cat_cols)

Index(['Rating', 'Size', 'Installs'], dtype='str')
Index(['App', 'Category', 'Reviews', 'Type', 'Price', 'Content Rating',
       'Genres', 'Last Updated', 'Current Ver', 'Android Ver'],
      dtype='str')

C:\Users\sahil\AppData\Local\Temp\ipykernel_15732\2400069286.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols=df.select_dtypes(include="object").columns

In [37]:
# univarient
# 1.distribution of app ratings
# 2. distribution of reviews
# 3. category distribution
# 4. type (free - paid ) distribution
# 5. top 15 categories

In [40]:
# bivarient 
# 1. Avg rating by category and plot the chart 
avg_rating = df.groupby("Category")["Rating"].mean().sort_values()
avg_rating

Category
DATING                  3.970769
TOOLS                   4.047411
MAPS_AND_NAVIGATION     4.051613
VIDEO_PLAYERS           4.063750
LIFESTYLE               4.094904
TRAVEL_AND_LOCAL        4.109292
BUSINESS                4.121452
ENTERTAINMENT           4.126174
FINANCE                 4.131889
NEWS_AND_MAGAZINES      4.132189
COMICS                  4.155172
COMMUNICATION           4.158537
FOOD_AND_DRINK          4.166972
LIBRARIES_AND_DEMO      4.178462
MEDICAL                 4.189143
AUTO_AND_VEHICLES       4.190411
PHOTOGRAPHY             4.192114
FAMILY                  4.192272
HOUSE_AND_HOME          4.197368
PRODUCTIVITY            4.211396
SPORTS                  4.223511
WEATHER                 4.244000
SOCIAL                  4.255598
SHOPPING                4.259664
HEALTH_AND_FITNESS      4.277104
BEAUTY                  4.278571
GAME                    4.286326
PARENTING               4.300000
PERSONALIZATION         4.335987
BOOKS_AND_REFERENCE     4.346067
ART_AND_DESIGN          4.358065
EDUCATION               4.389032
EVENTS                  4.435556
1.9                    19.000000
Name: Rating, dtype: float64

In [42]:
# free paid rating distribution
# rating vs reviews
# rating vs size
# installs by category
# average price by category
# reviews vs installs

In [43]:
# check missing values
df.isnull().sum()

App                   0
Category              0
Rating             1474
Reviews               0
Size               1696
Installs          10840
Type                  1
Price                 0
Content Rating        1
Genres                0
Last Updated          0
Current Ver           8
Android Ver           3
dtype: int64

In [44]:
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,NaN,NaN,Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,NaN,NaN,Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,NaN,NaN,Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37.0,NaN,Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,NaN,NaN,Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,NaN,NaN,Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,NaN,NaN,Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,NaN,NaN,Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86.0,NaN,Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24.0,NaN,Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [45]:
df.duplicated().sum()

np.int64(483)

In [46]:
# remove duplicate records
df.drop_duplicates(inplace=True)

In [47]:
# step 1: inspect the column installs 
df["Installs"].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Installs, dtype: float64