In [3]:
import pandas as pd

In [4]:
import numpy as np

In [6]:
df=pd.read_csv("students.csv")

In [7]:
df

   StudentID    Name  Age  Gender  Course  Marks           City
0        101  Shikha   22  Female  Python     85          Noida
1        102   Sahil   21    Male    Java     78          Delhi
2        103  Shital   32  Female  Python     92      Ghaziabad
3        104   Rohan   23    Male     C++     67          Noida
4        105   Priya   24  Female    Java     88          Delhi
5        106    Amit   22    Male  Python     75  Greater Noida
6        107    Neha   23  Female     C++     81      Ghaziabad
7        108     Raj   25    Male    Java     69          Delhi
8        109  Anjali   21  Female  Python     95          Noida
9        110   Vikas   24    Male     C++     72  Greater Noida

In [8]:
df.head()

   StudentID    Name  Age  Gender  Course  Marks       City
0        101  Shikha   22  Female  Python     85      Noida
1        102   Sahil   21    Male    Java     78      Delhi
2        103  Shital   32  Female  Python     92  Ghaziabad
3        104   Rohan   23    Male     C++     67      Noida
4        105   Priya   24  Female    Java     88      Delhi

In [9]:
df.head(10)

   StudentID    Name  Age  Gender  Course  Marks           City
0        101  Shikha   22  Female  Python     85          Noida
1        102   Sahil   21    Male    Java     78          Delhi
2        103  Shital   32  Female  Python     92      Ghaziabad
3        104   Rohan   23    Male     C++     67          Noida
4        105   Priya   24  Female    Java     88          Delhi
5        106    Amit   22    Male  Python     75  Greater Noida
6        107    Neha   23  Female     C++     81      Ghaziabad
7        108     Raj   25    Male    Java     69          Delhi
8        109  Anjali   21  Female  Python     95          Noida
9        110   Vikas   24    Male     C++     72  Greater Noida

In [10]:
df.tail()

   StudentID    Name  Age  Gender  Course  Marks           City
5        106    Amit   22    Male  Python     75  Greater Noida
6        107    Neha   23  Female     C++     81      Ghaziabad
7        108     Raj   25    Male    Java     69          Delhi
8        109  Anjali   21  Female  Python     95          Noida
9        110   Vikas   24    Male     C++     72  Greater Noida

In [11]:
df.tail()

   StudentID    Name  Age  Gender  Course  Marks           City
5        106    Amit   22    Male  Python     75  Greater Noida
6        107    Neha   23  Female     C++     81      Ghaziabad
7        108     Raj   25    Male    Java     69          Delhi
8        109  Anjali   21  Female  Python     95          Noida
9        110   Vikas   24    Male     C++     72  Greater Noida

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     str
 2   Age        10 non-null     int64
 3   Gender     10 non-null     str
 4   Course     10 non-null     str
 5   Marks      10 non-null     int64
 6   City       10 non-null     str
dtypes: int64(3), str(4)
memory usage: 692.0 bytes

In [13]:
df.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  23.700000  80.200000
std      3.02765   3.198958   9.670114
min    101.00000  21.000000  67.000000
25%    103.25000  22.000000  72.750000
50%    105.50000  23.000000  79.500000
75%    107.75000  24.000000  87.250000
max    110.00000  32.000000  95.000000

In [16]:
df.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City'], dtype='str')

In [18]:
df.size

70

In [20]:
df.shape

(10, 7)

In [22]:
df.sample()

   StudentID  Name  Age Gender  Course  Marks           City
5        106  Amit   22   Male  Python     75  Greater Noida

In [23]:
df.dtypes

StudentID    int64
Name           str
Age          int64
Gender         str
Course         str
Marks        int64
City           str
dtype: object

In [24]:
df.isnull()

   StudentID   Name    Age  Gender  Course  Marks   City
0      False  False  False   False   False  False  False
1      False  False  False   False   False  False  False
2      False  False  False   False   False  False  False
3      False  False  False   False   False  False  False
4      False  False  False   False   False  False  False
5      False  False  False   False   False  False  False
6      False  False  False   False   False  False  False
7      False  False  False   False   False  False  False
8      False  False  False   False   False  False  False
9      False  False  False   False   False  False  False

In [25]:
df.isnull().sum()

StudentID    0
Name         0
Age          0
Gender       0
Course       0
Marks        0
City         0
dtype: int64

In [29]:
df.isnotnull().sum()

AttributeError: 'DataFrame' object has no attribute 'isnotnull'

In [30]:
print(df["Name"])

0    Shikha
1     Sahil
2    Shital
3     Rohan
4     Priya
5      Amit
6      Neha
7       Raj
8    Anjali
9     Vikas
Name: Name, dtype: str

In [31]:
print(df[["Name","Age"]])

     Name  Age
0  Shikha   22
1   Sahil   21
2  Shital   32
3   Rohan   23
4   Priya   24
5    Amit   22
6    Neha   23
7     Raj   25
8  Anjali   21
9   Vikas   24

In [33]:
print(df[["Name","Age","Gender"]])

     Name  Age  Gender
0  Shikha   22  Female
1   Sahil   21    Male
2  Shital   32  Female
3   Rohan   23    Male
4   Priya   24  Female
5    Amit   22    Male
6    Neha   23  Female
7     Raj   25    Male
8  Anjali   21  Female
9   Vikas   24    Male

In [36]:
print(df[df["Marks"]>75])

   StudentID    Name  Age  Gender  Course  Marks       City
0        101  Shikha   22  Female  Python     85      Noida
1        102   Sahil   21    Male    Java     78      Delhi
2        103  Shital   32  Female  Python     92  Ghaziabad
4        105   Priya   24  Female    Java     88      Delhi
6        107    Neha   23  Female     C++     81  Ghaziabad
8        109  Anjali   21  Female  Python     95      Noida

In [43]:
df=df.set_index("StudentID")

In [44]:
df

             Name  Age  Gender  Course  Marks           City
StudentID
101        Shikha   22  Female  Python     85          Noida
102         Sahil   21    Male    Java     78          Delhi
103        Shital   32  Female  Python     92      Ghaziabad
104         Rohan   23    Male     C++     67          Noida
105         Priya   24  Female    Java     88          Delhi
106          Amit   22    Male  Python     75  Greater Noida
107          Neha   23  Female     C++     81      Ghaziabad
108           Raj   25    Male    Java     69          Delhi
109        Anjali   21  Female  Python     95          Noida
110         Vikas   24    Male     C++     72  Greater Noida

In [45]:
df.dropna()

             Name  Age  Gender  Course  Marks           City
StudentID
101        Shikha   22  Female  Python     85          Noida
102         Sahil   21    Male    Java     78          Delhi
103        Shital   32  Female  Python     92      Ghaziabad
104         Rohan   23    Male     C++     67          Noida
105         Priya   24  Female    Java     88          Delhi
106          Amit   22    Male  Python     75  Greater Noida
107          Neha   23  Female     C++     81      Ghaziabad
108           Raj   25    Male    Java     69          Delhi
109        Anjali   21  Female  Python     95          Noida
110         Vikas   24    Male     C++     72  Greater Noida

In [46]:
df.dropna(axis=0)

             Name  Age  Gender  Course  Marks           City
StudentID
101        Shikha   22  Female  Python     85          Noida
102         Sahil   21    Male    Java     78          Delhi
103        Shital   32  Female  Python     92      Ghaziabad
104         Rohan   23    Male     C++     67          Noida
105         Priya   24  Female    Java     88          Delhi
106          Amit   22    Male  Python     75  Greater Noida
107          Neha   23  Female     C++     81      Ghaziabad
108           Raj   25    Male    Java     69          Delhi
109        Anjali   21  Female  Python     95          Noida
110         Vikas   24    Male     C++     72  Greater Noida