In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("employees.csv")

In [4]:
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
0,101,Amit,IT,25,50000,2,Delhi,2022
1,102,Priya,HR,30,60000,5,Mumbai,2019
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
3,104,Neha,IT,35,80000,10,Delhi,2014
4,105,Vikas,Sales,27,45000,3,Chennai,2021
5,106,Anjali,HR,32,65000,7,Mumbai,2017
6,107,Karan,Finance,29,58000,5,Pune,2019
7,108,Meera,IT,26,52000,3,Bangalore,2021
8,109,Suresh,Sales,31,62000,6,Delhi,2018
9,110,Pooja,Finance,24,48000,1,Chennai,2023
10,111,Arjun,IT,38,90000,12,Pune,2012
11,112,Kavya,HR,29,61000,5,Bangalore,2019
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
13,114,Sneha,IT,27,54000,4,Delhi,2020
14,115,Deepak,Finance,36,85000,11,Chennai,2013

In [5]:
# display first 5 rows 
df.head()

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
0,101,Amit,IT,25,50000,2,Delhi,2022
1,102,Priya,HR,30,60000,5,Mumbai,2019
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
3,104,Neha,IT,35,80000,10,Delhi,2014
4,105,Vikas,Sales,27,45000,3,Chennai,2021

In [6]:
# display last 3 rows
df.tail(3)

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
13,114,Sneha,IT,27,54000,4,Delhi,2020
14,115,Deepak,Finance,36,85000,11,Chennai,2013

In [8]:
# find the number of rows and columns 
df.shape

(15, 8)

In [9]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Salary', 'Experience',
       'City', 'JoiningYear'],
      dtype='str')

In [10]:
df.dtypes

EmployeeID     int64
Name             str
Department       str
Age            int64
Salary         int64
Experience     int64
City             str
JoiningYear    int64
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   15 non-null     int64
 1   Name         15 non-null     str
 2   Department   15 non-null     str
 3   Age          15 non-null     int64
 4   Salary       15 non-null     int64
 5   Experience   15 non-null     int64
 6   City         15 non-null     str
 7   JoiningYear  15 non-null     int64
dtypes: int64(5), str(3)
memory usage: 1.1 KB

In [12]:
df.describe()

       EmployeeID        Age        Salary  Experience  JoiningYear
count   15.000000  15.000000     15.000000   15.000000    15.000000
mean   108.000000  30.000000  62333.333333    5.733333  2018.266667
std      4.472136   4.140393  13552.367567    3.283436     3.283436
min    101.000000  24.000000  45000.000000    1.000000  2012.000000
25%    104.500000  27.000000  53000.000000    3.500000  2016.500000
50%    108.000000  29.000000  60000.000000    5.000000  2019.000000
75%    111.500000  32.500000  67500.000000    7.500000  2020.500000
max    115.000000  38.000000  90000.000000   12.000000  2023.000000

In [19]:
# Check whether the dataset contains any missing values
df.isnull().sum()

EmployeeID     0
Name           0
Department     0
Age            0
Salary         0
Experience     0
City           0
JoiningYear    0
dtype: int64

In [20]:
# display the name column
df["Name"]

0       Amit
1      Priya
2      Rahul
3       Neha
4      Vikas
5     Anjali
6      Karan
7      Meera
8     Suresh
9      Pooja
10     Arjun
11     Kavya
12     Rohan
13     Sneha
14    Deepak
Name: Name, dtype: str

In [21]:
df[["Name","Salary"]]

      Name  Salary
0     Amit   50000
1    Priya   60000
2    Rahul   55000
3     Neha   80000
4    Vikas   45000
5   Anjali   65000
6    Karan   58000
7    Meera   52000
8   Suresh   62000
9    Pooja   48000
10   Arjun   90000
11   Kavya   61000
12   Rohan   70000
13   Sneha   54000
14  Deepak   85000

In [23]:
# Number of employees
df["EmployeeID"].count()

np.int64(15)

In [28]:
# Unique departments
df["Department"].unique()

<StringArray>
['IT', 'HR', 'Finance', 'Sales']
Length: 4, dtype: str

In [37]:
# Count employees in each department
df["Department"].value_counts()

Department
IT         5
Finance    4
HR         3
Sales      3
Name: count, dtype: int64

In [40]:
# Employee with highest salary
df.loc[df["Salary"].idxmax()]

EmployeeID       111
Name           Arjun
Department        IT
Age               38
Salary         90000
Experience        12
City            Pune
JoiningYear     2012
Name: 10, dtype: object

In [41]:
# Average salary
df["Salary"].mean()

np.float64(62333.333333333336)

In [43]:
# Employees in IT department
df[df["Department"]=="IT"]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
0,101,Amit,IT,25,50000,2,Delhi,2022
3,104,Neha,IT,35,80000,10,Delhi,2014
7,108,Meera,IT,26,52000,3,Bangalore,2021
10,111,Arjun,IT,38,90000,12,Pune,2012
13,114,Sneha,IT,27,54000,4,Delhi,2020

In [45]:
# Salary greater than 60000
df[df["Salary"]>60000]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
3,104,Neha,IT,35,80000,10,Delhi,2014
5,106,Anjali,HR,32,65000,7,Mumbai,2017
8,109,Suresh,Sales,31,62000,6,Delhi,2018
10,111,Arjun,IT,38,90000,12,Pune,2012
11,112,Kavya,HR,29,61000,5,Bangalore,2019
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
14,115,Deepak,Finance,36,85000,11,Chennai,2013

In [46]:
# Employees from Delhi
df[df["City"]=="Delhi"]

    EmployeeID    Name Department  Age  Salary  Experience   City  JoiningYear
0          101    Amit         IT   25   50000           2  Delhi         2022
3          104    Neha         IT   35   80000          10  Delhi         2014
8          109  Suresh      Sales   31   62000           6  Delhi         2018
13         114   Sneha         IT   27   54000           4  Delhi         2020

In [47]:
df.sort_values(by="Salary")

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
4,105,Vikas,Sales,27,45000,3,Chennai,2021
9,110,Pooja,Finance,24,48000,1,Chennai,2023
0,101,Amit,IT,25,50000,2,Delhi,2022
7,108,Meera,IT,26,52000,3,Bangalore,2021
13,114,Sneha,IT,27,54000,4,Delhi,2020
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
6,107,Karan,Finance,29,58000,5,Pune,2019
1,102,Priya,HR,30,60000,5,Mumbai,2019
11,112,Kavya,HR,29,61000,5,Bangalore,2019
8,109,Suresh,Sales,31,62000,6,Delhi,2018
5,106,Anjali,HR,32,65000,7,Mumbai,2017
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
3,104,Neha,IT,35,80000,10,Delhi,2014
14,115,Deepak,Finance,36,85000,11,Chennai,2013
10,111,Arjun,IT,38,90000,12,Pune,2012

In [49]:
# Find employees whose age is less than 30.
df[df["Age"]<30]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
0,101,Amit,IT,25,50000,2,Delhi,2022
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
4,105,Vikas,Sales,27,45000,3,Chennai,2021
6,107,Karan,Finance,29,58000,5,Pune,2019
7,108,Meera,IT,26,52000,3,Bangalore,2021
9,110,Pooja,Finance,24,48000,1,Chennai,2023
11,112,Kavya,HR,29,61000,5,Bangalore,2019
13,114,Sneha,IT,27,54000,4,Delhi,2020

In [51]:
# Find employees from Delhi and working in IT
df[(df["City"]=="Delhi") & (df["Department"]=="IT")]

    EmployeeID   Name Department  Age  Salary  Experience   City  JoiningYear
0          101   Amit         IT   25   50000           2  Delhi         2022
3          104   Neha         IT   35   80000          10  Delhi         2014
13         114  Sneha         IT   27   54000           4  Delhi         2020

In [52]:
# Find employees whose salary is between 50,000 and 70,000
df[(df["Salary"]>=50000) & (df["Salary"]<=70000)]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
0,101,Amit,IT,25,50000,2,Delhi,2022
1,102,Priya,HR,30,60000,5,Mumbai,2019
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
5,106,Anjali,HR,32,65000,7,Mumbai,2017
6,107,Karan,Finance,29,58000,5,Pune,2019
7,108,Meera,IT,26,52000,3,Bangalore,2021
8,109,Suresh,Sales,31,62000,6,Delhi,2018
11,112,Kavya,HR,29,61000,5,Bangalore,2019
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
13,114,Sneha,IT,27,54000,4,Delhi,2020

In [54]:
# Find employees who are not from Mumbai.
df[df["City"] != "Mumbai"]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
0,101,Amit,IT,25,50000,2,Delhi,2022
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
3,104,Neha,IT,35,80000,10,Delhi,2014
4,105,Vikas,Sales,27,45000,3,Chennai,2021
6,107,Karan,Finance,29,58000,5,Pune,2019
7,108,Meera,IT,26,52000,3,Bangalore,2021
8,109,Suresh,Sales,31,62000,6,Delhi,2018
9,110,Pooja,Finance,24,48000,1,Chennai,2023
10,111,Arjun,IT,38,90000,12,Pune,2012
11,112,Kavya,HR,29,61000,5,Bangalore,2019
13,114,Sneha,IT,27,54000,4,Delhi,2020
14,115,Deepak,Finance,36,85000,11,Chennai,2013

In [61]:
# Sort employees by salary (highest first).
df.sort_values(by="Salary", ascending=False)

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
10,111,Arjun,IT,38,90000,12,Pune,2012
14,115,Deepak,Finance,36,85000,11,Chennai,2013
3,104,Neha,IT,35,80000,10,Delhi,2014
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
5,106,Anjali,HR,32,65000,7,Mumbai,2017
8,109,Suresh,Sales,31,62000,6,Delhi,2018
11,112,Kavya,HR,29,61000,5,Bangalore,2019
1,102,Priya,HR,30,60000,5,Mumbai,2019
6,107,Karan,Finance,29,58000,5,Pune,2019
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
13,114,Sneha,IT,27,54000,4,Delhi,2020
7,108,Meera,IT,26,52000,3,Bangalore,2021
0,101,Amit,IT,25,50000,2,Delhi,2022
9,110,Pooja,Finance,24,48000,1,Chennai,2023
4,105,Vikas,Sales,27,45000,3,Chennai,2021

In [62]:
df.sort_values(by="Age" , ascending=True )

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
9,110,Pooja,Finance,24,48000,1,Chennai,2023
0,101,Amit,IT,25,50000,2,Delhi,2022
7,108,Meera,IT,26,52000,3,Bangalore,2021
4,105,Vikas,Sales,27,45000,3,Chennai,2021
13,114,Sneha,IT,27,54000,4,Delhi,2020
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
6,107,Karan,Finance,29,58000,5,Pune,2019
11,112,Kavya,HR,29,61000,5,Bangalore,2019
1,102,Priya,HR,30,60000,5,Mumbai,2019
8,109,Suresh,Sales,31,62000,6,Delhi,2018
5,106,Anjali,HR,32,65000,7,Mumbai,2017
12,113,Rohan,Sales,33,70000,8,Mumbai,2016
3,104,Neha,IT,35,80000,10,Delhi,2014
14,115,Deepak,Finance,36,85000,11,Chennai,2013
10,111,Arjun,IT,38,90000,12,Pune,2012

In [72]:
# Sort employees by Department and then Salary
df.sort_values(by=["Department","Salary"],ascending=[Tru)

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningYear
9,110,Pooja,Finance,24,48000,1,Chennai,2023
2,103,Rahul,Finance,28,55000,4,Bangalore,2020
6,107,Karan,Finance,29,58000,5,Pune,2019
14,115,Deepak,Finance,36,85000,11,Chennai,2013
1,102,Priya,HR,30,60000,5,Mumbai,2019
11,112,Kavya,HR,29,61000,5,Bangalore,2019
5,106,Anjali,HR,32,65000,7,Mumbai,2017
0,101,Amit,IT,25,50000,2,Delhi,2022
7,108,Meera,IT,26,52000,3,Bangalore,2021
13,114,Sneha,IT,27,54000,4,Delhi,2020
3,104,Neha,IT,35,80000,10,Delhi,2014
10,111,Arjun,IT,38,90000,12,Pune,2012
4,105,Vikas,Sales,27,45000,3,Chennai,2021
8,109,Suresh,Sales,31,62000,6,Delhi,2018
12,113,Rohan,Sales,33,70000,8,Mumbai,2016

In [64]:
# maxSalary
df["Salary"].max()

np.int64(90000)

In [65]:
# Find the minimum salary.
df["Salary"].min()

np.int64(45000)

In [68]:
# Find the average salary
df["Salary"].mean()

np.float64(62333.333333333336)

In [69]:
# Find the total salary paid to all employees.
df["Salary"].sum()

np.int64(935000)

In [71]:
# Count the number of employees
df["EmployeeID"].count()

np.int64(15)